# Generated by Django 4.2.7 on 2024-05-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lower_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='middle_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
