# Generated by Django 4.2.7 on 2024-05-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_image_lower_title_image_middle_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='middle_description',
            new_name='lower_description',
        ),
    ]
